Motivating (simple) example, we will implement:

> The k-times winsorized mean of a vector x is the mean of the elements of this vector, where each of its k smallest elements is replaced by the (k + 1)st smallest element, and similarly, each of the k largest elements is replaced by the (k + 1)st largest element

Julia has many standard data types

In [1]:
1

1

In [2]:
"Hello"

"Hello"

In [3]:
[1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [4]:
[1, 2, 3, 4, 5][1]

1

Types are important

In [5]:
typeof(1)

Int64

In [6]:
typeof("hi")

String

In [7]:
typeof(false)

Bool

Notice use of `{}` for generics 

In [8]:
typeof([1,2])

Vector{Int64} (alias for Array{Int64, 1})

In [9]:
x = 1

1

In [10]:
y = [1,2,3]
z = y
y[2] = 5
z

3-element Vector{Int64}:
 1
 5
 3

In [11]:
y = 1
z = y
y = 2
z

1

Has some nice latex-ish functionality around special characters e.g. `\epsilon` (use tab, tab)

In [12]:
ϵ = 2

2

In [13]:
if 2 > 1 
    "2 > 1"
elseif 1 > 2
    "1 > 2"
else
    "?"
end

"2 > 1"

In [14]:
0.1 + 0.2

0.30000000000000004

In [15]:
0.3 == (0.1 + 0.2)

false

`\approx` (will be operator version of `isapprox` function)

In [16]:
0.3 ≈ (0.1 + 0.2)

true

In [17]:
2 > 1 || 4 > 2

true

In [18]:
x = 4
x > 6 ? 1 : 2

2

In [19]:
?range

search: range LinRange UnitRange StepRange StepRangeLen trailing_zeros



```
range(start, stop, length)
range(start, stop; length, step)
range(start; length, stop, step)
range(;start, length, stop, step)
```

Construct a specialized array with evenly spaced elements and optimized storage (an [`AbstractRange`](@ref)) from the arguments. Mathematically a range is uniquely determined by any three of `start`, `step`, `stop` and `length`. Valid invocations of range are:

  * Call `range` with any three of `start`, `step`, `stop`, `length`.
  * Call `range` with two of `start`, `stop`, `length`. In this case `step` will be assumed to be one. If both arguments are Integers, a [`UnitRange`](@ref) will be returned.
  * Call `range` with one of `stop` or `length`. `start` and `step` will be assumed to be one.

See Extended Help for additional details on the returned type.

# Examples

```jldoctest
julia> range(1, length=100)
1:100

julia> range(1, stop=100)
1:100

julia> range(1, step=5, length=100)
1:5:496

julia> range(1, step=5, stop=100)
1:5:96

julia> range(1, 10, length=101)
1.0:0.09:10.0

julia> range(1, 100, step=5)
1:5:96

julia> range(stop=10, length=5)
6:10

julia> range(stop=10, step=1, length=5)
6:1:10

julia> range(start=1, step=1, stop=10)
1:1:10

julia> range(; length = 10)
Base.OneTo(10)

julia> range(; stop = 6)
Base.OneTo(6)

julia> range(; stop = 6.5)
1.0:1.0:6.0
```

If `length` is not specified and `stop - start` is not an integer multiple of `step`, a range that ends before `stop` will be produced.

```jldoctest
julia> range(1, 3.5, step=2)
1.0:2.0:3.0
```

Special care is taken to ensure intermediate values are computed rationally. To avoid this induced overhead, see the [`LinRange`](@ref) constructor.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.


!!! compat "Julia 1.7"
    The versions without keyword arguments and `start` as a keyword argument require at least Julia 1.7.


!!! compat "Julia 1.8"
    The versions with `stop` as a sole keyword argument, or `length` as a sole keyword argument require at least Julia 1.8.


---

REPL.Message("Extended help is available with `??`", (color = :cyan, bold = true))


In [20]:
for j in range(1,2,10)
    println(j)
end

1.0
1.1111111111111112
1.2222222222222223
1.3333333333333333
1.4444444444444444
1.5555555555555556
1.6666666666666667
1.7777777777777777
1.8888888888888888
2.0


In [21]:
for i in [1, 2, 3, 4]
  println(i)
end

1
2
3
4


Also have things like `while`. Blocks use `begin` and `end`.

In [22]:
begin
    x = 3
    x += 2
    x
end

5

In [23]:
# comment

In [24]:
function a(x)
    x + 12
end

a(12)

24

In [25]:
function g(x,y) 
    x + y
end

g(10,12)

22

In [26]:
# don't do this?

c(x) = begin
    y = x + 1
    return y
end

c(12)

13

In [27]:
b(x) = x - 12
b(24)

12

In [28]:
fancy(a, b = 12; c) = (a,b,c)

fancy (generic function with 2 methods)

In [29]:
fancy(1,2,3)

LoadError: MethodError: no method matching fancy(::Int64, ::Int64, ::Int64)
Closest candidates are:
  fancy(::Any, ::Any; c) at In[28]:1
  fancy(::Any) at In[28]:1

In [30]:
fancy(1,2,c=3)

(1, 2, 3)

In [31]:
fancy(1,c=3)

(1, 12, 3)

In [32]:
fancy2(a, b = 12; c, d = 4) = (a,b,c,d)

fancy2 (generic function with 2 methods)

In [33]:
fancy2(1, 2)

LoadError: UndefKeywordError: keyword argument c not assigned

In [34]:
fancy2(1,2,c=3,d=8)

(1, 2, 3, 8)

In [35]:
fancy2(1,2,c=3)

(1, 2, 3, 4)

In [36]:
f1 = y -> y + 2

f1(2)

4

In [37]:
map(x -> x ^ 3, [1, 2, 3, 4, 5])

5-element Vector{Int64}:
   1
   8
  27
  64
 125

In [38]:
sum(x -> x ^ 3, [1, 2, 3, 4])

100

Special `do/end` syntax; when *first* argument is a function with one argument:

In [39]:
sum([1, 2, 3, 4]) do x
   x ^ 3 
end

100

In [40]:
map([1,2,3]) do y
   y + 12 
end

3-element Vector{Int64}:
 13
 14
 15

Challenge from first chapter, write:

Motivating (simple) example, we will implement:

> The k-times winsorized mean of a vector x is the mean of the elements of this vector, where each of its k smallest elements is replaced by the (k + 1)st smallest element, and similarly, each of the k largest elements is replaced by the (k + 1)st largest element

Julia has many standard data types

In [41]:
function winsorized_mean(x, k)
    for i in range(1:k)
        
    end
end
    

winsorized_mean (generic function with 1 method)

One important note compared to other languages:

> In Julia, functions and for and while loops introduce a new scope, but if and begin-end blocks do not.

In [42]:
data = [1,2,3,12,213,232,23,232,23,213, -1232, -123]
n = 2

2

In [43]:
?sort

search: sort sort! sortperm sortperm! sortslices insorted Cshort issorted



```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Variant of [`sort!`](@ref) that returns a sorted copy of `v` leaving `v` itself unmodified.

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> sort(v)
3-element Vector{Int64}:
 1
 2
 3

julia> v
3-element Vector{Int64}:
 3
 1
 2
```

---

```
sort(A; dims::Integer, alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Sort a multidimensional array `A` along the given dimension. See [`sort!`](@ref) for a description of possible keyword arguments.

To sort slices of an array, refer to [`sortslices`](@ref).

# Examples

```jldoctest
julia> A = [4 3; 1 2]
2×2 Matrix{Int64}:
 4  3
 1  2

julia> sort(A, dims = 1)
2×2 Matrix{Int64}:
 1  2
 4  3

julia> sort(A, dims = 2)
2×2 Matrix{Int64}:
 3  4
 1  2
```


In [44]:
sorted_data = sort(data)

12-element Vector{Int64}:
 -1232
  -123
     1
     2
     3
    12
    23
    23
   213
   213
   232
   232

In [45]:
data

12-element Vector{Int64}:
     1
     2
     3
    12
   213
   232
    23
   232
    23
   213
 -1232
  -123

In [46]:
a10 = [[1,2]]

1-element Vector{Vector{Int64}}:
 [1, 2]

In [47]:
a11 = sort(a10)

1-element Vector{Vector{Int64}}:
 [1, 2]

In [48]:
a11[1][2] = 12

12

In [49]:
a10

1-element Vector{Vector{Int64}}:
 [1, 12]

In [50]:
1:10

1:10

In [51]:
for i in 1:n
   sorted_data[i] = sorted_data[n + 1]
end

In [52]:
sorted_data

12-element Vector{Int64}:
   1
   1
   1
   2
   3
  12
  23
  23
 213
 213
 232
 232

In [53]:
for i in 1:n
    sorted_data[i] = sorted_data[n + 1]
    sorted_data[end + 1 - i] = sorted_data[end - n]
end

In [54]:
sorted_data[end]

213

In [55]:
sorted_data

12-element Vector{Int64}:
   1
   1
   1
   2
   3
  12
  23
  23
 213
 213
 213
 213

In [56]:
sum(sorted_data) / length(sorted_data)

76.5

In [57]:
function winsorized_mean(x::Vector{Number}, k::Integer)
    sorted_x = sort(x)
    for i in 1:k
        sorted_x[i] = sorted_x[k + 1]
        sorted_x[end + 1 - i] = sorted_x[end - k]
    end
    sum(sorted_x) / length(sorted_x)
end

winsorized_mean (generic function with 2 methods)

In [58]:
winsorized_mean([1,2,3,12,213,232,23,232,23,213, -1232, -123], "yo")

LoadError: MethodError: no method matching (::Colon)(::Int64, ::String)
Closest candidates are:
  (::Colon)(::T, ::Any, ::T) where T<:Real at range.jl:41
  (::Colon)(::A, ::Any, ::C) where {A<:Real, C<:Real} at range.jl:10
  (::Colon)(::T, ::Any, ::T) where T at range.jl:40
  ...

In [59]:
methods(winsorized_mean)

# 2 methods for generic function "winsorized_mean":
[1] winsorized_mean(x::Vector{Number}, k::Integer) in Main at In[57]:1
[2] winsorized_mean(x, k) in Main at In[41]:1